### ISSUE TITLE
$*OS deprecation

### ISSUE THREAD

**Issue by MARTIMM** [tadzik/File-HomeDir#4]
I've forked your project and changed the file HomeDir.pm. Then uploaded with;

```
git remote add upstream https://github.com/tadzik/File-HomeDir.git
```

I wanted to change the $*OS and ended up changing a few extra things. I removed `unit` because  I also changed the class definition to be a black of code. I won't touch it now so you can see what is needed and what isn't.

`$*OS` is deprecated. I changed it into `$*KERNEL`. On my machine the `$*OS` also gives 'fedora'
which is not tested. `$*KERNEL` gives 'linux' with version info. Therefore I also changed the when arguments in regexes.

Greets
M

**Comment by tadzik** [comment]
Hey,
I didn't find your code pushed anywhere, but meanwhile @azawawi made a fork of File::HomeDir, available here: https://github.com/azawawi/File-HomeDir

It seems to fix the issue you pointed out, also being tested, more fleshed-out and with plans on being a proper Perl 5 port in general. I'm going to transfer the ownership of the project to him, and only keep this repository for historical reasons (or not at all).

I hope that his version works fine for you (since it uses $*KERNEL properly), but if it doesn't his repo is probably the best place to report any further bugs.

Thanks for your report though, good to hear that someone is looking after my broken stuff :)

**Comment by MARTIMM** [comment]
Hi,
Thanks for looking into it, In the mean time I get still the older version with panda. Perhaps the ecosystem must be changed to get the modules from there.
Greets
M

**Comment by azawawi** [comment]
Did you try `panda update && panda install File::HomeDir`?

**Comment by MARTIMM** [comment]
I only did an install, the panda update did the trick. I didn't know that the module list was updated by this.
Thanks
M
